Docerizing xarm grpc
Interactions-HSG/xarm-commander pull request #53
Opened 2022-02-28 13:11 UTC by S-Eibl

Add a Dockerfile to the xarm-grpc project. Loading cmake, grpc and the project on a Ubuntu 18.04.lts

2022-03-03 17:55 UTC, iomz requested changes
Please respect the commit log rules: https://github.com/Interactions-HSG/xarm-grpc/blob/main/CONTRIBUTING.md#commits

The resulting image from this Dockerfile is 3.28GB (!). Some parts can be optimized to reduce the final image. I'm pushing the changes.

Instead of using cmake, building xarm-grpc with Bazel would make things more straightforward(which I'm not familiar with...)
https://github.com/grpc/grpc/blob/master/BUILDING.md#building-with-bazel-recommended

2022-03-03 17:55 UTC, iomz commented on Dockerfile
> +FROM ubuntu:18.04 AS base
Why 18.04 instead of the latest LTS 20.04?

2022-03-03 17:55 UTC, iomz commented on Dockerfile
> +FROM extend-grpc AS xarm-grpc
Again, meaningless staging.

2022-03-03 17:55 UTC, iomz commented on Dockerfile
> +ENV CMAKE_VERSION=3.22.0
Do we really need v3.22.0 cmake?

2022-03-03 19:52 UTC, iomz commented
[792b745](https://github.com/Interactions-HSG/xarm-grpc/pull/53/commits/792b74591e66f2ba9a80f8d47b95ee192e2f07da) resolves #33 and #36

This is ugly. Further improvements are desired...

2022-03-03 20:07 UTC, iomz approved these changes
@S-Eibl Sorry for the destructive changes. What do you think?

2022-03-03 20:07 UTC, iomz commented on .github/workflows/docker-build.yml
> +          password: ${{ secrets.DOCKERHUB_TOKEN }}
Currently using my credential

2022-03-03 20:07 UTC, iomz commented on .github/workflows/docker-build.yml
> +          load: true
Not pushing to Docker Hub registry

2022-03-03 20:07 UTC, iomz commented on Dockerfile
> +FROM iomz/grpc-protoc:$GRPC_VERSION AS grpc
Since the gRPC image takes insanely long to build, I cheated here. I will come back to this with #54.

2022-03-03 20:07 UTC, iomz commented on Dockerfile
> +FROM gcc:$GCC_VERSION
This is also nasty. Ideally, I want to just cross-compile the binary for alpine...

2022-03-08 04:15 UTC, iomz commented
@S-Eibl I need your comment to merge this PR.

2022-03-08 13:44 UTC, merged

2022-03-08 16:25 UTC, iomz commented
I didn't ask you to merge silently...

2022-03-08 17:08 UTC, S-Eibl commented
Oh sorry, should I revert that?

2022-03-09 10:08 UTC, iomz commented
> Oh sorry, should I revert that?

Nope, it would've been just nice if you "responded" to the comments/review/code, e.g., "Looks good to me", "I don't understand this: ...", "This part needs to be revised in the following manner in the future", etc. The reviewing is a process of problem resolution, and without it, it is hard to track the decision making process of the developers (us).